# Generated by Django 2.0.7 on 2018-07-22 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('topic', models.CharField(max_length=30)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='snippet',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Status'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='tag',
            field=models.ManyToManyField(related_name='snippet', to='creator.Tags'),
        ),
    ]
